project:
  type: book
  output-dir: _book

book:
  title: "Biological and Biomedical Data Science ([DSAN 6150](https://gu-dsan.github.io/6150-fall-2024/){target=_blank})"
  author: "Abhijit Dasgupta, PhD"
  page-footer:
    left: |
      Copyright Abhijit Dasgupta (2024). All rights reserved
    right: |
      This book was built with <a href="https://quarto.org">Quarto</a>
  license: "CC BY"
  date: last-modified
  date-format: long
  site-url: https://www.araastat.com/6150-notes
  repo-url: https://github.com/araastat/6150-notes/
  repo-branch: main
  repo-actions: [edit,issue]
  chapters:
    - index.qmd
    - summary.qmd
    - references.qmd
  appendices:
    - 01-technical-background.qmd
bibliography: references.bib

format:
  html:
    theme: cosmo
    code-link: true
    callout-appearance: simple



